# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sources/main_application.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from src.utils import singleton, user_input_event_manager
from src.models.game.hangman_game import user_input_queue


@singleton
class Ui_HangManGame(object):
    def setup_ui(self, HangManGame):
        HangManGame.setObjectName("HangManGame")
        HangManGame.resize(480, 640)
        HangManGame.setMinimumSize(QtCore.QSize(480, 640))
        HangManGame.setMaximumSize(QtCore.QSize(480, 640))
        HangManGame.setBaseSize(QtCore.QSize(480, 640))

        self.titleLabel = QtWidgets.QLabel(HangManGame)
        self.titleLabel.setEnabled(True)
        self.titleLabel.setGeometry(QtCore.QRect(0, 0, 480, 70))

        font = QtGui.QFont()
        font.setFamily("Apple LiGothic")
        font.setPointSize(70)
        font.setBold(True)
        font.setWeight(75)

        self.titleLabel.setFont(font)
        self.titleLabel.setAutoFillBackground(False)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")

        self.gameLogFrame = QtWidgets.QFrame(HangManGame)
        self.gameLogFrame.setGeometry(QtCore.QRect(0, 380, 480, 180))
        self.gameLogFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gameLogFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gameLogFrame.setObjectName("gameLogFrame")

        self.gameLogTextBox = QtWidgets.QTextEdit(self.gameLogFrame)
        self.gameLogTextBox.setGeometry(QtCore.QRect(20, 20, 440, 140))
        self.gameLogTextBox.setReadOnly(True)
        self.gameLogTextBox.setObjectName("gameLogTextBox")

        self.userInputFrame = QtWidgets.QFrame(HangManGame)
        self.userInputFrame.setGeometry(QtCore.QRect(0, 560, 480, 80))
        self.userInputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.userInputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.userInputFrame.setObjectName("userInputFrame")

        self.userInputTextEdit = QtWidgets.QTextEdit(self.userInputFrame)
        self.userInputTextEdit.setGeometry(QtCore.QRect(10, 10, 360, 60))

        font = QtGui.QFont()
        font.setFamily("NanumGothic")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)

        self.userInputTextEdit.setFont(font)
        self.userInputTextEdit.setObjectName("userInputTextEdit")

        self.inputButton = QtWidgets.QPushButton(self.userInputFrame)
        self.inputButton.setGeometry(QtCore.QRect(400, 0, 80, 80))
        self.inputButton.setObjectName("inputButton")
        self.inputButton.clicked.connect(self.get_user_input)

        self.gameImageFrame = QtWidgets.QFrame(HangManGame)
        self.gameImageFrame.setGeometry(QtCore.QRect(0, 70, 480, 310))
        self.gameImageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gameImageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gameImageFrame.setObjectName("gameImageFrame")

        self.hangManImage = QtWidgets.QLabel(self.gameImageFrame)
        self.hangManImage.setGeometry(QtCore.QRect(40, 20, 400, 270))
        self.hangManImage.setScaledContents(True)  # 이미지 크기에 맞게 조정
        self.hangManImage.setObjectName("hangManImage")

        self.retranslate_ui(HangManGame)

        QtCore.QMetaObject.connectSlotsByName(HangManGame)

    def retranslate_ui(self, HangManGame):
        _translate = QtCore.QCoreApplication.translate
        HangManGame.setWindowTitle(_translate("HangManGame", "HangManGame"))
        self.titleLabel.setText(_translate("HangManGame", "Hang Man Game"))
        self.userInputTextEdit.setPlaceholderText(
            _translate("HangManGame", "알파벳 소문자 1글자만 입력 해주세요 (종료를 원하시면 \"종료\" 라고 입력 해주세요)"))
        self.inputButton.setText(_translate("HangManGame", "제출"))

    def get_user_input(self) -> None:
        # 사용자 입력값을 받고 초기화
        user_input = self.userInputTextEdit.toPlainText()
        self.clear_user_input_text_edit()

        # input 버튼을 통해서 직접적인 값 return은 지원하지 않기에, user_input_queue에 값을 넣어두고 필요한곳에서 활용
        user_input_queue.append(user_input)
        print(user_input_queue)

        # Queue에 값 추가되고, event set
        user_input_event_manager.set_event()

    # 행맨의 이미지를 변경하는 메서드
    def update_hangman_image(self, image_path):
        pixmap = QtGui.QPixmap(image_path)
        self.hangManImage.setPixmap(pixmap)

    # 게임 로그를 업데이트하는 메서드
    def update_game_log_text_box(self, message: str) -> None:
        # self.clear_game_log_text_box()
        # self.gameLogTextBox.setText(message)
        cursor = self.gameLogTextBox.textCursor()
        cursor.movePosition(QtGui.QTextCursor.End)
        cursor.insertText(message + "\n")
        self.scrollDown()

    # 텍스트 박스를 맨 밑으로 스크롤 다운하는 메서드
    def scrollDown(self):
        scrollbar = self.gameLogTextBox.verticalScrollBar()
        scrollbar.setValue(scrollbar.maximum())

    # 게임 로그를 초기화하는 메서드 (니즈에 따라, 삭제가 아닌 빈칸 추가로 기존 데이터를 남기는 방향으로 고려될 수 있음)
    def clear_game_log_text_box(self) -> None:
        self.gameLogTextBox.clear()

    # 사용자 입력 텍스트 박스를 초기화하는 메서드
    def clear_user_input_text_edit(self) -> None:
        self.userInputTextEdit.clear()
